### ISSUE TITLE
Changing parent_id doesn't calculate id_paths for model with parents

### ISSUE THREAD

**Issue by jaycode** [bandito/acts_as_tree_on_steroids#2]
Check out my fork for fix

**Comment by jaycode** [comment]
http://github.com/jaycode/acts_as_tree_on_steroids

**Comment by bandito** [comment]
Thanks

I just merged it. Tests run ok. It would be great if we added a test for that specific case.

Thanks again.

**Comment by jaycode** [comment]
I thank you for the great module. I am afraid I don't think I'll have the time anytime sooner to add test cases. Plus the problem is very specific to my problem... (a tweak is needed when the model is not activerecord base class)
